# Get custom lambda image
FROM public.ecr.aws/lambda/python:latest

# Preform dark arts I do not understand
ARG UNIXODBC_VERSION=2.3.12

RUN dnf install -y gzip tar openssl-devel gcc gcc-c++ make automake kernel-devel

RUN curl ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-${UNIXODBC_VERSION}.tar.gz -O \
    && tar xzvf unixODBC-${UNIXODBC_VERSION}.tar.gz \
    && cd unixODBC-${UNIXODBC_VERSION} \
    && ./configure --sysconfdir=/opt --disable-gui --disable-drivers --enable-iconv --with-iconv-char-enc=UTF8 --with-iconv-ucode-enc=UTF16LE --prefix=/opt \
    && make \
    && make install

RUN curl https://packages.microsoft.com/config/rhel/9/prod.repo > /etc/yum.repos.d/mssql-release.repo
RUN dnf install -y e2fsprogs fuse-libs libss
RUN ACCEPT_EULA=Y dnf install -y msodbcsql18

ENV CFLAGS="-I/opt/include"
ENV LDFLAGS="-L/opt/lib"

RUN mkdir /opt/python/ && cd /opt/python/ && pip install pyodbc -t .

RUN dnf install -y openssl

# Set lambda root as working directory
WORKDIR ${LAMBDA_TASK_ROOT}

# Copy and install requirements
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy dependant files
COPY extract.py .
COPY transform.py .
COPY load_master_data.py .
COPY insert_transactional_data.py .
COPY load.py .

# Copy main ETL script and run

COPY run_etl.py .
CMD [ "run_etl.lambda_handler" ]
