name: Pylint Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install requirements and pylint
      run: | 
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.py
    - name: Run pylint
      run: |
        pylint --fail-under 9 *.py
  
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: 'pip'
    - name: Install requirements.txt and pytest
      run: | 
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r [requirements file path]
    - name: Run tests
      run: |
        pytest test_*.py
