name: Pylint and Pytest Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-short-term-etl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install requirements and pylint
      run: |
        cd short-term-etl
        pip install -r requirements.txt
    - name: Run pylint
      run: |
        find . -type f -name "*.py" -maxdepth 1 | \
        xargs pylint --disable=I1101
  lint-long-term-etl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install requirements and pylint
      run: |
        cd long-term-etl
        pip install -r requirements.txt
    - name: Run pylint
      run: |
        find . -type f -name "*.py" -maxdepth 1 | \
        xargs pylint --disable=I1101
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: 'pip'
    - name: Install requirements.txt and pytest
      run: | 
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r short-term-etl/requirements.txt
    - name: Run tests
      run: |
        cd short-term-etl
        pytest test_*.py
